
spring:
  application:
    name: ACDelivery

#  datasource:
#    url: jdbc:postgresql://localhost:5432/acdelivery
#    username: postgres
#    password: Job@259
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://dpg-d3op8c3ipnbc739djplg-a.singapore-postgres.render.com:5432/acdelivery
    username: acdelivery_user
    password: 4wSEmp12h47r0SiXta1W6UWX72cGfx6c
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: bW9ja1NlY3JldEtleU15U3VwZXJTZWNyZXRLZXkzMjEhQA==
  expiration: 86400000

app:
  upload:
    dir: C:\D\ac-ecommerce\uploads

logging:
  level:
    org.springframework.security: DEBUG
